pipeline {
    agent any

   

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                 checkout scm
            }
        }

        stage('Terraform Init') {
            steps {

               dir('eks-terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('eks-terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                sdir('eks-terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('eks-terraform') {
                    sh 'terraform init'
                }
            }
        }
    }

    post {
        success {
            echo 'EKS Infrastructure Deployed Successfully!'
        }
        failure {
            echo 'Pipeline Failed!'
        }
    }
}
