pipeline {
    agent any

  

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                 checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                sh  'terraform init -upgrade'
               
            }
        }

        stage('Terraform Validate') {
            steps {
                sh 'terraform validate'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan -out=tfplan'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve tfplan'
            }
        }
    }

    post {
        success {
            echo 'EKS Infrastructure Deployed Successfully!'
        }
        failure {
            echo 'Pipeline Failed!'
        }
    }
}
