pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('tERRAFORM') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('tERRAFORM') {
                    withCredentials([file(credentialsId: 'terraform-dev-tfvars', variable: 'terraform-dev-tfvars')])
                    sh 'terraform plan'
                }
            }
        }

       /* stage('Approval') {
            steps {
                input message: 'Do you want to apply Terraform changes?'
            }
        }
*/
        stage('Terraform Apply') {
            steps {
                dir('tERRAFORM') {
                    withCredentials([file(credentialsId: 'terraform-dev-tfvars', variable: 'terraform-dev-tfvars')])
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
